linters:
  enable:
    - structcheck
    - varcheck
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - golint
    - ineffassign
    - vet
    - unused
    - misspell
    - bodyclose
    - interfacer
    - unconvert
    - maligned
    # - depguard
    - nakedret
    - prealloc
    - whitespace
  disable:
    - errcheck

run:
  deadline: 3m
  skip-dirs:
    - bin
    - docs
