linters:
  enable:
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - revive
    - ineffassign
    - govet
    - unused
    - misspell
    - bodyclose
    - unconvert
    - nakedret
    - prealloc
    - whitespace
  disable:
    - errcheck

run:
  deadline: 3m
  issues.exclude-dirs:
    - bin
    - docs
