version: "2"
linters:
  enable:
    - govet
    - ineffassign
    - unused
    - bodyclose
    - misspell
    - nakedret
    - prealloc
    - revive
    - unconvert
    - whitespace
    - errcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: bin
      - path: (.+)\.go$
        text: docs
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
