version: 2

run:
  timeout: 3m

linters:
  enable:
    - staticcheck
    - unconvert
    - revive  # replacement for golint
    - ineffassign
    - govet
    - unused
    - misspell
    - bodyclose
    - nakedret
    - prealloc
    - whitespace
  disable:
    - errcheck

issues:
  exclude-dirs:
    - bin
    - docs
