project_name: "Podsync"

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/podsync/
    binary: podsync
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64

archives:
  - id: arc
    name_template: >-
      {{- .ProjectName }}_{{.Version}}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ .Tag }}-next'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch

release:
  # We publish Docker image manually,
  # include links to the release notes.
  footer: |
    # Docker images
    ```
    docker pull ghcr.io/mxpv/podsync:{{ .Tag }}
    docker pull ghcr.io/mxpv/podsync:latest
    ```
