// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package handler is a generated GoMock package.
package handler

import (
	gomock "github.com/golang/mock/gomock"
	patreon_go "github.com/mxpv/patreon-go"
	api "github.com/mxpv/podsync/pkg/api"
	reflect "reflect"
)

// MockfeedService is a mock of feedService interface
type MockfeedService struct {
	ctrl     *gomock.Controller
	recorder *MockfeedServiceMockRecorder
}

// MockfeedServiceMockRecorder is the mock recorder for MockfeedService
type MockfeedServiceMockRecorder struct {
	mock *MockfeedService
}

// NewMockfeedService creates a new mock instance
func NewMockfeedService(ctrl *gomock.Controller) *MockfeedService {
	mock := &MockfeedService{ctrl: ctrl}
	mock.recorder = &MockfeedServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockfeedService) EXPECT() *MockfeedServiceMockRecorder {
	return m.recorder
}

// CreateFeed mocks base method
func (m *MockfeedService) CreateFeed(req *api.CreateFeedRequest, identity *api.Identity) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFeed", req, identity)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFeed indicates an expected call of CreateFeed
func (mr *MockfeedServiceMockRecorder) CreateFeed(req, identity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFeed", reflect.TypeOf((*MockfeedService)(nil).CreateFeed), req, identity)
}

// BuildFeed mocks base method
func (m *MockfeedService) BuildFeed(hashID string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildFeed", hashID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildFeed indicates an expected call of BuildFeed
func (mr *MockfeedServiceMockRecorder) BuildFeed(hashID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildFeed", reflect.TypeOf((*MockfeedService)(nil).BuildFeed), hashID)
}

// GetMetadata mocks base method
func (m *MockfeedService) GetMetadata(hashID string) (*api.Metadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata", hashID)
	ret0, _ := ret[0].(*api.Metadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadata indicates an expected call of GetMetadata
func (mr *MockfeedServiceMockRecorder) GetMetadata(hashID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockfeedService)(nil).GetMetadata), hashID)
}

// Downgrade mocks base method
func (m *MockfeedService) Downgrade(patronID string, featureLevel int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Downgrade", patronID, featureLevel)
	ret0, _ := ret[0].(error)
	return ret0
}

// Downgrade indicates an expected call of Downgrade
func (mr *MockfeedServiceMockRecorder) Downgrade(patronID, featureLevel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Downgrade", reflect.TypeOf((*MockfeedService)(nil).Downgrade), patronID, featureLevel)
}

// MockpatreonService is a mock of patreonService interface
type MockpatreonService struct {
	ctrl     *gomock.Controller
	recorder *MockpatreonServiceMockRecorder
}

// MockpatreonServiceMockRecorder is the mock recorder for MockpatreonService
type MockpatreonServiceMockRecorder struct {
	mock *MockpatreonService
}

// NewMockpatreonService creates a new mock instance
func NewMockpatreonService(ctrl *gomock.Controller) *MockpatreonService {
	mock := &MockpatreonService{ctrl: ctrl}
	mock.recorder = &MockpatreonServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockpatreonService) EXPECT() *MockpatreonServiceMockRecorder {
	return m.recorder
}

// Hook mocks base method
func (m *MockpatreonService) Hook(pledge *patreon_go.Pledge, event string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hook", pledge, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Hook indicates an expected call of Hook
func (mr *MockpatreonServiceMockRecorder) Hook(pledge, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hook", reflect.TypeOf((*MockpatreonService)(nil).Hook), pledge, event)
}

// GetFeatureLevelByID mocks base method
func (m *MockpatreonService) GetFeatureLevelByID(patronID string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeatureLevelByID", patronID)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetFeatureLevelByID indicates an expected call of GetFeatureLevelByID
func (mr *MockpatreonServiceMockRecorder) GetFeatureLevelByID(patronID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeatureLevelByID", reflect.TypeOf((*MockpatreonService)(nil).GetFeatureLevelByID), patronID)
}

// GetFeatureLevelFromAmount mocks base method
func (m *MockpatreonService) GetFeatureLevelFromAmount(amount int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeatureLevelFromAmount", amount)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetFeatureLevelFromAmount indicates an expected call of GetFeatureLevelFromAmount
func (mr *MockpatreonServiceMockRecorder) GetFeatureLevelFromAmount(amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeatureLevelFromAmount", reflect.TypeOf((*MockpatreonService)(nil).GetFeatureLevelFromAmount), amount)
}
